name: Check PR
on:
  schedule:
    - cron: "*/1 * * * * "
jobs:
  check-pr-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/check-pr-ci@v1
        with:
          filter-label: 'automerge'
          filter-head-ref: 'content'
          success-review: true
          success-merge: true
          merge-method: 'squash'
          merge-title: 'Auto merge master to content'
          failure-close: true