name: Create production promotion pull request
on:
  push:
    branches:
      - master
jobs:
  contentSyncwithProduction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: content
      - name: Reset promotion branch
        run: |
          git fetch origin master:master
          git reset --hard master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: content